# Generated by Django 5.0.4 on 2024-05-28 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0003_remove_interpretacion_id_actor_and_more'),
        ('reserva', '0002_alter_entrada_id_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='id_pelicula',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='id_sala',
        ),
        migrations.AddField(
            model_name='sesion',
            name='pelicula',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, related_name='pelicula', to='cartelera.pelicula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='reserva.sala'),
            preserve_default=False,
        ),
    ]
