# Generated by Django 5.0.4 on 2024-05-28 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0003_remove_interpretacion_id_actor_and_more'),
        ('reserva', '0003_remove_sesion_id_pelicula_remove_sesion_id_sala_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='pelicula',
        ),
        migrations.RemoveField(
            model_name='sesion',
            name='sala',
        ),
        migrations.AddField(
            model_name='sesion',
            name='id_pelicula',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sesion',
            name='id_sala',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='reserva.sala'),
            preserve_default=False,
        ),
    ]
