# Generated by Django 5.0.4 on 2024-05-28 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0006_rename_pelicula_sesion_id_pelicula_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='id_sala',
        ),
        migrations.AddField(
            model_name='sesion',
            name='sala',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sala', to='reserva.sala'),
            preserve_default=False,
        ),
    ]
