# Generated by Django 5.0.4 on 2024-05-28 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0007_remove_sesion_id_sala_sesion_sala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sesion',
            name='fecha',
        ),
    ]
