# Generated by Django 5.0.4 on 2024-05-28 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0009_entrada_fecha_compra'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entrada',
            old_name='id_sesion',
            new_name='sesion',
        ),
        migrations.RenameField(
            model_name='entrada',
            old_name='id_usuario',
            new_name='usuario',
        ),
    ]
