# Generated by Django 5.0.4 on 2024-05-28 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0010_rename_id_sesion_entrada_sesion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='sala',
            new_name='id_sala',
        ),
    ]
