# Generated by Django 5.0.4 on 2024-05-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0012_rename_id_sala_sesion_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='sala',
            new_name='id_sala',
        ),
    ]
