# Generated by Django 5.0.4 on 2024-05-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0014_rename_id_sala_sesion_sala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sesion',
            old_name='id_pelicula',
            new_name='pelicula',
        ),
    ]
