# Generated by Django 5.0.4 on 2024-05-29 11:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_tipoentrada'),
        ('reserva', '0015_rename_id_pelicula_sesion_pelicula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entrada',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='entrada',
            name='precio',
        ),
        migrations.AddField(
            model_name='entrada',
            name='tipo_entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='compra.tipoentrada'),
            preserve_default=False,
        ),
    ]
