# Generated by Django 5.0.4 on 2024-05-29 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0017_sillon_alter_sesion_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sillon',
            name='estado',
            field=models.TextField(default='libre'),
        ),
    ]
