# Generated by Django 5.0.4 on 2024-05-29 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0019_sala_sillones_sesion_sillones_ocupados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sillon',
            name='estado',
        ),
    ]
