# Generated by Django 5.0.4 on 2024-05-30 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0020_remove_sillon_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrada',
            name='sillon',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reserva.sillon'),
            preserve_default=False,
        ),
    ]
