# Generated by Django 5.0.4 on 2024-06-05 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0021_entrada_sillon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sesion',
            name='sillones_ocupados',
            field=models.ManyToManyField(blank=True, to='reserva.sillon'),
        ),
    ]
