# Generated by Django 5.0.4 on 2024-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0023_alter_sillon_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='nombre',
            field=models.TextField(unique=True),
        ),
    ]
