# Generated by Django 5.0.4 on 2024-04-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('apellidos', models.TextField()),
                ('email', models.TextField()),
                ('fecha_nacimiento', models.DateField()),
                ('password', models.TextField()),
                ('es_admin', models.BooleanField()),
            ],
        ),
    ]
