# Generated by Django 5.0.4 on 2024-05-28 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacion', '0001_initial'),
        ('reserva', '0002_alter_entrada_id_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
