# Generated by Django 5.0.4 on 2024-05-13 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='descripcion',
            field=models.TextField(default='descripcion por defecto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menu',
            name='nombre',
            field=models.TextField(default='nombre por defecto'),
            preserve_default=False,
        ),
    ]
