# Generated by Django 5.0.4 on 2024-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0002_menu_descripcion_menu_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='foto',
            field=models.ImageField(default='foto', upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bebida',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='comida',
            name='foto',
            field=models.ImageField(upload_to=''),
        ),
    ]
