# Generated by Django 5.0.4 on 2024-05-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0003_menu_foto_alter_bebida_foto_alter_comida_foto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='id_bebida',
            new_name='bebida',
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='id_comida',
            new_name='comida',
        ),
    ]
