# Generated by Django 5.0.4 on 2024-05-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0004_rename_id_bebida_menu_bebida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField()),
                ('foto', models.ImageField(upload_to='')),
                ('precio', models.FloatField()),
            ],
        ),
    ]
