# Generated by Django 5.0.4 on 2024-06-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0005_tipoentrada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comida',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
