# Generated by Django 5.0.4 on 2024-04-23 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('link_imdb', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pegi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_trailer', models.TextField()),
                ('cartel', models.TextField()),
                ('fecha_lanzamiento', models.DateField()),
                ('director', models.TextField()),
                ('titulo', models.TextField()),
                ('duracion', models.FloatField()),
                ('sinopsis', models.TextField()),
                ('id_pegi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pegi')),
            ],
        ),
        migrations.CreateModel(
            name='Interpretacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.actor')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula')),
            ],
        ),
        migrations.CreateModel(
            name='PeliculaGenero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.genero')),
                ('id_pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cartelera.pelicula')),
            ],
        ),
    ]
