# Generated by Django 5.0.4 on 2024-05-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelicula',
            name='cartel',
            field=models.ImageField(upload_to=''),
        ),
    ]
