# Generated by Django 5.0.4 on 2024-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartelera', '0002_alter_pelicula_cartel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interpretacion',
            name='id_actor',
        ),
        migrations.RemoveField(
            model_name='peliculagenero',
            name='id_genero',
        ),
        migrations.RemoveField(
            model_name='interpretacion',
            name='id_pelicula',
        ),
        migrations.RemoveField(
            model_name='pelicula',
            name='id_pegi',
        ),
        migrations.RemoveField(
            model_name='peliculagenero',
            name='id_pelicula',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='actores',
            field=models.TextField(default='Hanna Montanah, Freddie Mercury, Jack Black, Tom Hanks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='genero',
            field=models.TextField(default='Accion, Aventura, Fantasia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pelicula',
            name='pegi',
            field=models.TextField(default='+7'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Actor',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.DeleteModel(
            name='Interpretacion',
        ),
        migrations.DeleteModel(
            name='Pegi',
        ),
        migrations.DeleteModel(
            name='PeliculaGenero',
        ),
    ]
